name: CI

on:
  push:
    branches:
      - main  # Change this to your default branch
  pull_request:
    branches:
      - main  # Change this to your default branch

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: nouchka/sqlite3:latest  # Or another DB service if needed
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Use the version that matches your local environment

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure this file lists all necessary packages

    - name: Run tests
      run: |
        pytest test_auth.py  # Change this to your main test command
