name: CI

on:
  push:
    branches:
      - main  # Change this to your default branch
  pull_request:
    branches:
      - main  # Change this to your default branch

jobs:
  test:
    runs-on: ubuntu-latest  # Windows is also fine, but Ubuntu has more native support for GitHub Actions

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Match with your local version if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure this file lists all necessary packages

    - name: Run tests
      run: |
        pytest test_auth.py --disable-warnings --maxfail=1  # Adapt this command if needed for additional options
